name: devel-cuda
on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".*"
      - "tool/**"
jobs:
  build-cuda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Follows the pytorch supported CUDA versions.
        cuda_version: ["11.3.1"]
        cudnn_version: ["8"]
        ubuntu_version: ["20.04"]
        python_version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Docker build & push
        run: |
          export TAG=devel-cuda${{ matrix.cuda_version }}-cudnn${{ matrix.cudnn_version }}-ubuntu${{ matrix.ubuntu_version }}-python${{ matrix.python_version }}

          docker build \
            --no-cache \
            --progress=plain \
            --build-arg CUDA_VERSION=${{ matrix.cuda_version }} \
            --build-arg CUDNN_VERSION=${{ matrix.cudnn_version }} \
            --build-arg UBUNTU_VERSION=${{ matrix.ubuntu_version }} \
            --build-arg PYTHON_VERSION=${{ matrix.python_version }} \
            -t wden/wden:"$TAG" \
            -f dockerfile/devel_cuda \
            .

          docker login --username=wden --password=${{ secrets.DOCKER_PASSWORD }}
          docker push wden/wden:"$TAG"

          docker login \
            --username="${{ secrets.HUAWEICLOUD_AREA }}@${{ secrets.HUAWEICLOUD_AK }}" \
            --password=${{ secrets.HUAWEICLOUD_TOKEN }} \
            "swr.${{ secrets.HUAWEICLOUD_AREA }}.myhuaweicloud.com"
          docker tag wden/wden:"$TAG" swr."${{ secrets.HUAWEICLOUD_AREA }}".myhuaweicloud.com/wden/wden:"$TAG"
          docker push swr."${{ secrets.HUAWEICLOUD_AREA }}".myhuaweicloud.com/wden/wden:"$TAG"
  build-cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: ["20.04"]
        python_version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2

      - name: Docker build & push
        run: |
          export TAG=devel-cpu-ubuntu${{ matrix.ubuntu_version }}-python${{ matrix.python_version }}

          docker build \
            --no-cache \
            --progress=plain \
            --build-arg UBUNTU_VERSION=${{ matrix.ubuntu_version }} \
            --build-arg PYTHON_VERSION=${{ matrix.python_version }} \
            -t wden/wden:"$TAG" \
            -f dockerfile/devel_cpu \
            .

          docker login --username=wden --password=${{ secrets.DOCKER_PASSWORD }}
          docker push wden/wden:"$TAG"

          docker login \
            --username="${{ secrets.HUAWEICLOUD_AREA }}@${{ secrets.HUAWEICLOUD_AK }}" \
            --password=${{ secrets.HUAWEICLOUD_TOKEN }} \
            "swr.${{ secrets.HUAWEICLOUD_AREA }}.myhuaweicloud.com"
          docker tag wden/wden:"$TAG" swr."${{ secrets.HUAWEICLOUD_AREA }}".myhuaweicloud.com/wden/wden:"$TAG"
          docker push swr."${{ secrets.HUAWEICLOUD_AREA }}".myhuaweicloud.com/wden/wden:"$TAG"
